---
title: "Storm_Data_Analysis"
output: html_document
date: "2023-08-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Loading and Processing Data

```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)
df = read_csv("repdata_data_StormData.csv", col_names = TRUE, show_col_types = FALSE) %>% clean_names()
```


```{r}
dim(df) #size
colnames(df) #Col Names
head(df,10)
```

##EXPLORING EXPONENTS AND ASSIGN VALUES

```{r}
df %>% select(cropdmgexp) %>% table()
```

```{r}
propexp_lookup = c("-"=1, "?"=1, "+"=1, "0"=1, "1"=10, "2"=100, "3"=1000,
                   "4"=10000, "5"=100000, "6"=1000000, "7"=10000000, "8"=100000000, "h"=100, "H"=100, "k"=1000, "m"=1000000, "M"=1000000, "B"=1000000000)
cropexp_lookup = c("?"=1, "2"=100, "k"=1000, "m"=1000000, "M"=1000000, "B"=1000000000)
df1 = df1 %>% mutate(propexp_val = recode(propdmgexp, !!!propexp_lookup, .missing = 1), cropexp_val = recode(cropdmgexp,!!!cropexp_lookup, .missing = 1)) %>% select(-c("cropdmgexp", "propdmgexp"))
df1 = df1 %>% mutate(dmg_total = (propdmg * propexp_val +cropdmg * cropexp_val))
```

#CALCULATE TOTAL CASUALTIES (INJURIES + FATALITIES)

```{r}
df1 = df1 %>% mutate(casualties_total = (injuries + fatalities))
head(df1)
```

#RESULTS
## Events that are most harmful with respect to population health

```{r}
df_health = df1 %>% group_by(evtype) %>% sumarise(injuries=sum(injuries), fatalities=sum(fatalities), total_casualties=sum(casualties_total)) %>% arrange(desc(total_casualties))
df_health %>% head(10)
```

```{r}
df_health %>% head(5) %>% pivot_longer(cols = injuries:total_casualties) %>% ggplot(aes(x=reorder(evtype, -value), y=value, fill=as.factor(name))) + geom_col(position = "dodge") + labs(title = "Storm events with most casualties", x="Event Types", y="Count") + scale_fill_discrete(name="", labels=c("Facilities", "Injuries", "Total Casualties"))
```

```{r}
df_econ = df1 %>% group_by(evtype) %>% sumarise(total_damage=sum(dmg_total)) %>% arrange(desc(total_damage))
df_econ %>% head(10)
```

```{r}
options(scipen = 999)
df_econ %>% head(5) %>% ggplot(aes(x=reorder(evtype, -total_damage), y=total_damage/1000000000, fill="brown")) + geom_col() + labs(title = "Storm events with most economic damage", x="Event Type", y="Damage($ Billions)") + theme(legend.position = "none")
```


